In [2]:
import pandas as pd

In [28]:

# set the max columns to none
pd.set_option('display.max_columns', None)


df = pd.read_csv('data/NYCgov Poverty Measure Data/NYCgov_Poverty_Measure_Data__2018_.csv')

## Data Observations

,SERIALNO,SPORDER,PWGTP,WGTP,AGEP,CIT,REL,SCH,SCHG,SCHL,SEX,ESR,LANX,ENG,MSP,MAR,WKW,WKHP,DIS,JWTR,NP,TEN,HHT,AgeCateg,Boro,CitizenStatus,EducAttain,EST_Childcare,EST_Commuting,EST_EITC,EST_FICAtax,EST_HEAP,EST_Housing,EST_IncomeTax,EST_MOOP,EST_Nutrition,EST_PovGap,EST_PovGapIndex,Ethnicity,FamType_PU,FTPTWork,INTP_adj,MRGP_adj,NYCgov_Income,NYCgov_Pov_Stat,NYCgov_REL,NYCgov_Threshold,Off_Pov_Stat,Off_Threshold,OI_adj,PA_adj,Povunit_ID,Povunit_Rel,PreTaxIncome_PU,RETP_adj,RNTP_adj,SEMP_adj,SSIP_adj,SSP_adj,TotalWorkHrs_PU,WAGP_adj
64,1054,1,344,344,34,1,0,1,0,15.0,2,1.0,2.0,NaN,6.0,5,1.0,40,2,4.0,1,3,6,2,1,1,1.0,0.0,1230.000,0.0,1627.54030,21.0,0.0000,1784.2529,690.00,1158.0,0.0000,0.000000,4,8,1,0.0,0.0,17122.244,2,0,16241.600,2,13064,0.0,0.0,1,1,21275.037,0.0000,1317.02610,0.0,0.0,0.000,3,21275.037
99,1862,1,54,55,84,1,0,1,0,16.0,2,6.0,2.0,NaN,3.0,2,NaN,0,1,NaN,1,2,6,3,1,1,2.0,0.0,0.000,0.0,0.00000,0.0,3326.3276,0.0000,2973.00,0.0,3731.1074,0.229725,1,8,3,0.0,0.0,12510.492,1,0,16241.600,2,12043,0.0,0.0,1,1,12157.164,0.0000,0.00000,0.0,0.0,12157.164,5,0.000
104,1982,1,72,73,48,5,0,1,0,24.0,1,1.0,1.0,1.0,1.0,1,1.0,40,2,1.0,4,3,1,2,1,3,4.0,0.0,8565.583,0.0,11237.77800,0.0,1782.9078,30807.3030,7568.00,0.0,0.0000,0.000000,4,2,1,0.0,0.0,90503.313,2,0,42861.836,2,25900,0.0,0.0,1,1,146899.060,0.0000,1519.64550,0.0,0.0,0.000,1,70916.789
105,1982,2,61,73,46,5,1,1,0,21.0,2,1.0,1.0,1.0,1.0,1,1.0,40,2,1.0,4,3,1,2,1,3,4.0,0.0,8565.583,0.0,11237.77800,0.0,1782.9078,30807.3030,7568.00,0.0,0.0000,0.000000,4,2,1,0.0,0.0,90503.313,2,1,42861.836,2,25900,0.0,0.0,1,2,146899.060,0.0000,1519.64550,0.0,0.0,0.000,1,75982.273
106,1982,3,80,73,20,5,2,1,0,17.0,1,6.0,1.0,1.0,6.0,5,NaN,0,2,NaN,4,3,1,2,1,3,2.0,0.0,8565.583,0.0,11237.77800,0.0,1782.9078,30807.3030,7568.00,0.0,0.0000,0.000000,4,2,3,0.0,0.0,90503.313,2,2,42861.836,2,25900,0.0,0.0,1,4,146899.060,0.0000,1519.64550,0.0,0.0,0.000,1,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68237,1400411,1,161,161,52,4,0,1,0,15.0,2,1.0,2.0,NaN,2.0,1,1.0,40,2,4.0,1,3,6,2,1,2,1.0,0.0,1230.000,0.0,775.01923,35.0,7133.0615,-500.0000,2172.04,0.0,2619.6270,0.161291,2,8,1,0.0,0.0,13621.973,1,0,16241.600,1,13064,0.0,0.0,1,1,10130.970,0.0000,810.47760,0.0,0.0,0.000,3,10130.970
68245,1400518,1,356,356,74,2,0,1,0,19.0,2,1.0,1.0,1.0,4.0,3,1.0,25,2,7.0,1,3,6,3,1,1,3.0,0.0,4062.000,0.0,1309.78250,0.0,5114.3276,1056.2876,2563.80,0.0,0.0000,0.000000,4,8,2,0.0,0.0,27731.084,2,0,16241.600,2,12043,0.0,0.0,1,1,31608.627,1215.7164,384.97687,0.0,0.0,13271.570,4,17121.340
68264,1400910,1,201,201,48,4,0,1,0,21.0,2,1.0,1.0,1.0,4.0,3,1.0,35,2,2.0,3,3,3,2,1,2,4.0,0.0,1476.000,0.0,3487.58640,0.0,0.0000,5270.9688,1901.04,0.0,1590.2306,0.045378,4,6,1,0.0,0.0,33453.770,1,0,35044.000,2,19642,0.0,0.0,1,1,45589.363,0.0000,911.78729,0.0,0.0,0.000,2,39510.781
68265,1400910,2,222,201,78,5,6,1,0,9.0,1,3.0,1.0,4.0,1.0,1,NaN,0,2,NaN,3,3,3,3,1,3,1.0,0.0,1476.000,0.0,3487.58640,0.0,0.0000,5270.9688,1901.04,0.0,1590.2306,0.045378,4,6,3,0.0,0.0,33453.770,1,4,35044.000,2,19642,0.0,0.0,1,4,45589.363,0.0000,911.78729,0.0,0.0,0.000,2,0.000
68266,1400910,3,189,201,65,5,6,1,0,11.0,2,1.0,1.0,4.0,1.0,1,5.0,40,2,2.0,3,3,3,3,1,3,1.0,0.0,1476.000,0.0,3487.58640,0.0,0.0000,5270.9688,1901.04,0.0,1590.2306,0.045378,4,6,2,0.0,0.0,33453.770,1,4,35044.000,2,19642,0.0,0.0,1,4,45589.363,0.0000,911.78729,0.0,0.0,0.000,2,6078.582

In [38]:
df[df['Boro'] == 1 ].describe()

,SERIALNO,SPORDER,PWGTP,WGTP,AGEP,CIT,REL,SCH,SCHG,SCHL,SEX,ESR,LANX,ENG,MSP,MAR,WKW,WKHP,DIS,JWTR,NP,TEN,HHT,AgeCateg,Boro,CitizenStatus,EducAttain,EST_Childcare,EST_Commuting,EST_EITC,EST_FICAtax,EST_HEAP,EST_Housing,EST_IncomeTax,EST_MOOP,EST_Nutrition,EST_PovGap,EST_PovGapIndex,Ethnicity,FamType_PU,FTPTWork,INTP_adj,MRGP_adj,NYCgov_Income,NYCgov_Pov_Stat,NYCgov_REL,NYCgov_Threshold,Off_Pov_Stat,Off_Threshold,OI_adj,PA_adj,Povunit_ID,Povunit_Rel,PreTaxIncome_PU,RETP_adj,RNTP_adj,SEMP_adj,SSIP_adj,SSP_adj,TotalWorkHrs_PU,WAGP_adj
count,9.806000e+03,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9467.000000,9806.000000,7725.000000,9246.000000,5341.000000,7891.000000,9806.000000,4554.000000,9806.000000,9806.000000,3992.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.0,9806.000000,9467.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9.806000e+03,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000,9806.000000
mean,7.117290e+05,2.368040,141.672955,134.741689,38.014175,2.327147,2.372221,1.294412,2.738629,14.674871,1.548950,3.188867,1.422345,1.781689,3.873907,3.529370,1.828063,16.976239,1.840506,3.592936,3.736080,2.600653,2.446767,1.904650,1.0,1.522231,2.151262,930.191475,1994.325896,292.374234,4915.659299,12.197419,4138.294323,8669.563542,4282.371088,2316.886677,2441.357956,0.085353,3.047012,3.516520,2.246992,634.281799,314.512998,59888.801180,1.742097,1.909749,33574.951789,1.758617,23410.478177,361.332418,103.518554,1.038956,2.262492,7.409418e+04,1466.968805,833.589767,760.421349,412.222826,1855.175252,2.740261,18860.739787
std,4.016681e+05,1.663194,98.367067,91.332388,23.018829,1.655320,3.465035,0.611719,5.055643,6.037817,0.497624,2.401704,0.493960,1.001632,2.185838,1.776814,1.598537,19.840171,0.366155,2.836368,2.249165,0.771110,1.595177,0.620888,0.0,0.762765,1.139137,4603.344126,2381.892318,1053.043260,6857.315778,34.417733,6071.765363,31890.426395,5549.159927,3147.146579,5837.775944,0.198580,1.178393,2.425532,0.873649,9701.308036,842.069894,54626.799443,0.437503,2.553759,12920.135562,0.427944,9030.508143,3474.667852,824.306151,0.249245,1.198092,9.464375e+04,8345.245865,678.906123,8582.266872,1924.271432,5343.959400,1.508414,42235.932207
min,1.054000e+03,1.000000,14.000000,21.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,0.000000,0.000000,-65.806030,0.000000,0.000000,0.000000,-21993.029000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,-1620.955200,0.000000,-13878.849000,1.000000,0.000000,16241.600000,1.000000,12043.000000,0.000000,0.000000,1.000000,1.000000,-2.937981e+03,0.000000,0.000000,-6787.750000,0.000000,0.000000,1.000000,0.000000
25%,3.719570e+05,1.000000,75.000000,72.000000,18.000000,1.000000,0.000000,1.000000,0.000000,11.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,2.000000,1.000000,2.000000,2.000000,1.000000,2.000000,1.0,1.000000,1.000000,0.000000,147.600010,0.000000,775.019230,0.000000,0.000000,-1269.200000,272.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,0.000000,0.000000,28722.779000,1.000000,0.000000,22900.654000,2.000000,16815.000000,0.000000,0.000000,1.000000,1.000000,2.127504e+04,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,7.103290e+05,2.000000,115.000000,111.000000,37.000000,1.000000,2.000000,1.000000,0.000000,16.000000,2.000000,1.000000,1.000000,1.000000,4.000000,5.000000,1.000000,0.000000,2.000000,4.000000,3.000000,3.000000,2.000000,2.000000,1.0,1.000000,2.000000,0.000000,1230.000000,0.000000,3169.828600,0.000000,0.000000,1273.271600,2411.500000,926.250000,0.000000,0.000000,4.000000,3.000000,3.000000,0.000000,0.000000,47469.613500,2.000000,2.000000,35044.000000,2.000000,20212.000000,0.000000,0.000000,1.000000,2.000000,4.959110e+04,0.000000,952.311160,0.000000,0.000000,0.000000,3.000000,0.000000
75%,1.062593e+06,3.000000,179.750000,171.000000,56.000000,4.000000,2.000000,2.000000,3.000000,19.000000,2.000000,6.000000,2.000000,3.000000,6.000000,5.000000,1.000000,40.000000,2.000000,4.000000,5.000000,3.000000,3.000000,2.000000,1.0,2.000000,3.000000,0.000000,2706.000000,0.000000,6654.159700,21.000000,6891.265600,9959.774400,6325.080100,3540.250000,401.336415,0.013640,4.000000,6.000000,3.000000,0.000000,0.000000,74774.055000,2.000000,2.000000,42861.836000,2.000000,29509.000000,0.000000,0.000000,1.000000,3.000000,9.523112e+04,0.000000,1317.026100,0.000000,0.000000,0.000000,4.000000,25327.426000
max,1.400910e+06,20.000000,1178.000000,970.000000,95.000000,5.000000,15.000000,3.000000,16.000000,24.000000,2.000000,6.000000,2.000000,4.000000,6.000000,5.000000,6.000000,99.000000,2.000000,12.000000,20.000000,4.000000,7.000000,3.000000,1.0,3.000000,4.000000,48263.754000,17206.033000,6431.000000,80436.727000,1061.630000,36710.223000,576009.560000,56418.039000,18437.500000,51140.430000,1.000000,5.000000,8.000000,3.000000,336348.220000,7091.679200,761915.190000,2.000000,12.000000,95162.492000,2.000000,55883.000000,83073.953000,16412.172000,6.000000,4.000000,1.432519e+06,148925.270000,3241.910400,389029.250000,24922.186000,35458.395000,5.000000,668644.000000

## Data Analysis

In [64]:


#Data Analysis
class Codes:
    def __init__(self):
        #Borough Codes
        self.BRONX = 1
        self.BROOKLYN  = 2
        self.MANHATTAN = 3
        self.QUEENS = 4
        self.STATEN_ISLAND = 5
        
        #Ethinicity
        self.WHITE = 1 
        self.BLACK = 2  
        self.ASIAN = 3
        self.HISPANIC  = 4
        self.ETHNICITY_OTHER = 5
        
        
codes = Codes()

class BoroStruct:
    def __init__(self, name, code, population):
        self.name = name
        self.code = code
        self.population = population
        self.pov_rate = -1
        
        self.white_rate = -1
        self.black_rate =  -1
        self.asian_rate = -1
        self.hispanic_rate  = -1
        self.other_rate = -1
    
        
    def set_pov_rate(self, pov_rate):
        self.pov_rate = pov_rate

    def set_white_rate(self, white_rate):
        self.white_rate = white_rate
    
    def set_black_rate(self, black_rate):
        self.black_rate = black_rate
    
    def set_asian_rate(self, asian_rate):
        self.asian_rate = asian_rate

    def set_hispanic_rate(self, hispanic_rate):
        self.hispanic_rate = hispanic_rate
    
    def set_other_rate(self, other_rate):
        self.other_rate = other_rate
        
    def to_string(self):
        return "Name: " + str(self.name) + "\nCode: " + str(self.code) +  "\nPopulation: " + str(self.population)+ "\nPorverty Rate: " + str(self.pov_rate) + "\nWhite percentage: " + str(self.white_rate) + "\nBlack percentage: " + str(self.black_rate) + "\nAsian percentage: " + str(self.asian_rate) + "\nHispanic percentage: " + str(self.hispanic_rate) + "\nOther percentage: " + str(self.other_rate)

    
    
def calc_boro_population(boro_code):
    return len(df[df['Boro'] == boro_code])

boroughs = [
    BoroStruct("Bronx", codes.BRONX, calc_boro_population(codes.BRONX)),
    BoroStruct('Brooklyn', codes.BROOKLYN, calc_boro_population(codes.BROOKLYN)),
    BoroStruct('Manhattan', codes.MANHATTAN, calc_boro_population(codes.MANHATTAN)),
    BoroStruct('Queens', codes.QUEENS, calc_boro_population(codes.QUEENS)),
    BoroStruct('Staten Island', codes.STATEN_ISLAND, calc_boro_population(codes.STATEN_ISLAND))
] 


OFF_POV_STAT = 1


def calc_pov_rate(boro):
    num_pov = len(df[(df['Boro'] == boro.code) & (df['Off_Pov_Stat'] == OFF_POV_STAT)])
    return (num_pov/boro.population)


for i in range(len(boroughs)):
    curr = boroughs[i]
    boroughs[i].set_pov_rate(calc_pov_rate(curr))
#     print(curr.to_string(),  "\n")


def calc_ethinicity_rate(ethnicity_code, boro):
    num_race = len(df[(df['Boro'] == boro.code) & (df['Ethnicity'] == ethnicity_code)])
    #print("calc Ethc: ", boro.code,  " ", ethnicity_code, " Number: ", num_race, " Population: ", boro.population, "Perc: ",  (num_race/boro.population)) Test
    
    return (num_race/boro.population)
    
    
for i in range(len(boroughs)):
    curr = boroughs[i]
    
    boroughs[i].set_white_rate(calc_ethinicity_rate(codes.WHITE, curr ))
    boroughs[i].set_black_rate(calc_ethinicity_rate(codes.BLACK, curr ))
    boroughs[i].set_asian_rate(calc_ethinicity_rate(codes.ASIAN, curr ))
    boroughs[i].set_hispanic_rate(calc_ethinicity_rate(codes.HISPANIC, curr ))
    boroughs[i].set_other_rate(calc_ethinicity_rate(codes.ETHNICITY_OTHER , curr ))
    
    
def print_all():
    for i in range(len(boroughs)):
            print(boroughs[i].to_string() + "\n")
            
            
print_all()

Name: Bronx
Code: 1
Population: 9806
Porverty Rate: 0.24138282684070977
White percentage: 0.12900265143789516
Black percentage: 0.26504181113603914
Asian percentage: 0.05568019579849072
Hispanic percentage: 0.5304915357944116
Other percentage: 0.01978380583316337

Name: Brooklyn
Code: 2
Population: 24184
Porverty Rate: 0.15191862388355937
White percentage: 0.42747270922924246
Black percentage: 0.24044823023486603
Asian percentage: 0.1477836586172676
Hispanic percentage: 0.15216672179953689
Other percentage: 0.032128680119087

Name: Manhattan
Code: 3
Population: 9065
Porverty Rate: 0.13127413127413126
White percentage: 0.5075565361279647
Black percentage: 0.10854936569222283
Asian percentage: 0.13281853281853281
Hispanic percentage: 0.21853281853281853
Other percentage: 0.03254274682846112

Name: Queens
Code: 4
Population: 21198
Porverty Rate: 0.09656571374657986
White percentage: 0.2801679403717332
Black percentage: 0.16058118690442494
Asian percentage: 0.27611095386357204
Hispanic percentage: 0.2359656571374658
Other percentage: 0.04717426172280404

Name: Staten Island
Code: 5
Population: 4020
Porverty Rate: 0.09850746268656717
White percentage: 0.6412935323383084
Black percentage: 0.08258706467661692
Asian percentage: 0.11492537313432835
Hispanic percentage: 0.1407960199004975
Other percentage: 0.020398009950248756

In [57]:
df.columns

Index(['SERIALNO', 'SPORDER', 'PWGTP', 'WGTP', 'AGEP', 'CIT', 'REL', 'SCH',
       'SCHG', 'SCHL', 'SEX', 'ESR', 'LANX', 'ENG', 'MSP', 'MAR', 'WKW',
       'WKHP', 'DIS', 'JWTR', 'NP', 'TEN', 'HHT', 'AgeCateg', 'Boro',
       'CitizenStatus', 'EducAttain', 'EST_Childcare', 'EST_Commuting',
       'EST_EITC', 'EST_FICAtax', 'EST_HEAP', 'EST_Housing', 'EST_IncomeTax',
       'EST_MOOP', 'EST_Nutrition', 'EST_PovGap', 'EST_PovGapIndex',
       'Ethnicity', 'FamType_PU', 'FTPTWork', 'INTP_adj', 'MRGP_adj',
       'NYCgov_Income', 'NYCgov_Pov_Stat', 'NYCgov_REL', 'NYCgov_Threshold',
       'Off_Pov_Stat', 'Off_Threshold', 'OI_adj', 'PA_adj', 'Povunit_ID',
       'Povunit_Rel', 'PreTaxIncome_PU', 'RETP_adj', 'RNTP_adj', 'SEMP_adj',
       'SSIP_adj', 'SSP_adj', 'TotalWorkHrs_PU', 'WAGP_adj'],
      dtype='object')

In [6]:
#Percentage of people in poverty 
#Bronx -> 1
#Brooklyn -> 2

IS_POV = '1'
NOT_POV = '2'

boro = '2'

total_people = (df['Boro'] == '2').s
num_people_in_pov = len(df['Off_Pov_Stat'] == NOT_POV ) 

perc_people_pov = (num_people_in_pov/total_people)

print("Num People in borough:", total_people)
print('Num people in pov: ', num_people_in_pov)
print('percentage of people in poverty',  perc_people_pov)

Num People in borough: 0
Num people in pov:  68273
percentage of people in poverty inf

<ipython-input-6-9d5cd7371e5b>:15: RuntimeWarning: divide by zero encountered in longlong_scalars
  perc_people_pov = (num_people_in_pov/total_people)

In [ ]:
#Race percentage composition per borough